#! /usr/bin/env fish
# :vim: ft=fish

set --local lid_state_file /proc/acpi/button/lid/LID0/state
if test -r $lid_state_file
    test "open" = (sed -e 's/^.*  *//' $lid_state_file)
else
    false
end
