- name: brew casks to install
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - iterm2
    - firefox
    - slack
    - avira-antivirus
    - java8
    - sublime-text
    - vagrant
    - virtualbox
    - intellij-idea
    - tunnelblick
    - flux
    - google-chrome
  when: ansible_system == 'Darwin'
