- name: brew casks to install
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - iterm2
    - flux
    - firefox
    - google-chrome
    - slack
    - tunnelblick
    - authy
    - avira-antivirus
    - gpg-suite
    - java8
    - google-cloud-sdk
    - sublime-text
    - vagrant
    - virtualbox
    - intellij-idea
    - razorsql
  when: ansible_system == 'Darwin'
